/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_kmar_game_ConsoleUtils */

#ifndef _Included_top_kmar_game_ConsoleUtils
#define _Included_top_kmar_game_ConsoleUtils
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     top_kmar_game_ConsolePrinter
 * Method:    init
 */
JNIEXPORT void JNICALL Java_top_kmar_game_ConsolePrinter_initN
  (JNIEnv *, jclass, jint, jint, jint, jint);

JNIEXPORT void JNICALL Java_top_kmar_game_ConsolePrinter_flushN
        (JNIEnv *, jclass, jint);

JNIEXPORT void JNICALL Java_top_kmar_game_ConsolePrinter_quickFillAtrN
        (JNIEnv *, jclass, jint, jint, jint, jint, jint);

JNIEXPORT void JNICALL Java_top_kmar_game_ConsolePrinter_quickFillCharN
        (JNIEnv *, jclass, jchar, jint, jint, jint, jint);

/*
 * Class:     top_kmar_game_ConsolePrinter
 * Method:    fillRect
 */
JNIEXPORT void JNICALL Java_top_kmar_game_ConsolePrinter_fillRectN
        (JNIEnv *, jclass, jchar, jint, jint, jint, jint, jint);

JNIEXPORT void JNICALL Java_top_kmar_game_ConsolePrinter_fillRectAttrN
        (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     top_kmar_game_ConsolePrinter
 * Method:    fillRectHollow
 */
JNIEXPORT void JNICALL Java_top_kmar_game_ConsolePrinter_fillRectHollowN
        (JNIEnv *, jclass, jchar, jint, jint, jint, jint, jint, jint);

/*
 * Class:     top_kmar_game_ConsolePrinter
 * Method:    fillRectHollow
 */
JNIEXPORT void JNICALL Java_top_kmar_game_ConsolePrinter_drawStringN
        (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jint);

JNIEXPORT void JNICALL Java_top_kmar_game_ConsolePrinter_modifyAttrN
        (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
